# 1. 텐서

텐서(Tensor)는 파이토치의 기본 단위이며 GPU 연산을 가능하게 한다. 또한 Numpy의 배열과 유사하여 손쉽게 다룰 수 있다.

## 1.1 텐서 만들기

In [ ]:
# 라이브러리 불러오기
import torch # Pytorch를 사용하기 위한 기본 라이브러리다.
import numpy as np # Numpy를 사용하기 위한 기본 라이브러리다. 여기서 "as np"는 numpy를 np로 짧게 표기하겠다는 뜻이다.

In [ ]:
# 빈 텐서 생성
x = torch.empty(5,4) # 5x4 행렬 생성
print(x) # 초기화되지 않은 행렬인 경우 해당 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타난다.

tensor([[ 0.0000e+00,  4.5893e-41, -3.2747e+19,  4.5893e-41],
        [-3.4959e+19,  4.5893e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-3.2747e+19,  4.5893e-41, -3.2747e+19,  4.5893e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [ ]:
torch.ones(3,3) # 3x3 일 행렬

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2) # 2행 영 벡터

tensor([0., 0.])

In [ ]:
torch.rand(5,6) # 5x6 랜덤 행렬

tensor([[0.6953, 0.5575, 0.8612, 0.0831, 0.2603, 0.3333],
        [0.3582, 0.5100, 0.5921, 0.4203, 0.1730, 0.0758],
        [0.7540, 0.3492, 0.8815, 0.1784, 0.6594, 0.7023],
        [0.9063, 0.6140, 0.0146, 0.6832, 0.3827, 0.2804],
        [0.1019, 0.5452, 0.1893, 0.7391, 0.2785, 0.2275]])

## 1.2 리스트, 넘파이 배열을 텐서로 만들기

In [ ]:
l = [13,4] # 리스트 생성
r = np.array([4,56,7]) # 넘파이 배열 생성

In [ ]:
torch.tensor(l) # 리스트를 텐서로 쉽게 변환할 수 있다.

tensor([13,  4])

In [ ]:
torch.tensor(r) #넘파이 배열을 텐서로 쉽게 변환할 수 있다.

tensor([ 4, 56,  7])

In [ ]:
torch.FloatTensor(r)

tensor([ 4., 56.,  7.])

## 1.3 텐서의 크기와 타입 확인하기

In [ ]:
x.size()

torch.Size([5, 4])

In [ ]:
x.shape

torch.Size([5, 4])

In [ ]:
x.size()[1] # .size()는 텐서의 크기를 확인할 수 있으며 매우 자주 사용된다.

4

In [ ]:
type(x) # type은 Python에서 사용되는 모든 것들을 종류를 보여준다.

torch.Tensor

## 1.4 텐서의 덧셈

In [ ]:
x = torch.rand(2,2) # 2x2 랜덤 행렬
y = torch.rand(2,2) # 2x2 랜덤 행렬
print(x)
print(y)

tensor([[0.7604, 0.6263],
        [0.8528, 0.1525]])
tensor([[0.8151, 0.7981],
        [0.9878, 0.7293]])


In [ ]:
x+y # 두 텐서의 합

tensor([[1.5755, 1.4243],
        [1.8406, 0.8818]])

In [ ]:
torch.add(x,y) # 두 텐서의 합의 또 다른 표현

tensor([[1.5755, 1.4243],
        [1.8406, 0.8818]])

In [ ]:
y.add(x) # 두 텐서의 합의 또 다른 표현이지만 이는 y에 x를 더한다는 의미다.

tensor([[1.5755, 1.4243],
        [1.8406, 0.8818]])

In [ ]:
print("원래 y: ", y)
y.add_(x)
print("y=y+x: ",y)

# y = y+x
# y.add_는 y에 x를 더한 값을 y에 대체한다.(inplace 방식)

원래 y:  tensor([[0.8151, 0.7981],
        [0.9878, 0.7293]])
y=y+x:  tensor([[1.5755, 1.4243],
        [1.8406, 0.8818]])


## 1.5 텐서의 크기 변환하기

In [ ]:
x = torch.rand(8,8) # 8x8 랜덤 행렬
print(x.size())

torch.Size([8, 8])


In [ ]:
a = x.view(64) # 크기를 바꿔주는 view 8x8 -> 64
print(a.size())

torch.Size([64])


In [ ]:
b = x.view(-1,4,4) # -1은 원래 크기가 되게 하는 값 8x8 -> -1x4x4 즉, 4x4x4이다.
print(b.size())

# 따라서 -1은 원래 크기가 되게 하는 값이 자동으로 지정되기 때문에 한 번만 사용할 수 있다.
# 예를 들어 x.view(-1,-1,4)와 같은 선언은 오류가 난다.

torch.Size([4, 4, 4])


## 1.6 텐서에서 넘파이로 만들기

In [ ]:
x = torch.rand(8,8)
y = x.numpy() # .numpy()로 매우 간단하게 넘파이 배열로 만들 수 있다.
print(y)

[[0.58490604 0.60596395 0.7062497  0.3433159  0.46974093 0.13365442
  0.18695915 0.8097575 ]
 [0.514391   0.04686153 0.5443974  0.16235709 0.16069686 0.5957702
  0.3840499  0.11374015]
 [0.76672834 0.08444566 0.76016366 0.24253374 0.5309299  0.2524582
  0.7406843  0.26290596]
 [0.06949955 0.17845273 0.37473398 0.9946809  0.9250965  0.46990597
  0.89662486 0.42212754]
 [0.6524946  0.81468594 0.9332604  0.37116224 0.9142144  0.232867
  0.4932257  0.38809645]
 [0.14773053 0.16449535 0.83779997 0.32437438 0.7680281  0.89530027
  0.7503912  0.629459  ]
 [0.01401812 0.1876995  0.11132312 0.7373625  0.3974368  0.47767997
  0.95073265 0.43383163]
 [0.04517156 0.17624354 0.6115043  0.6161139  0.46460146 0.35296023
  0.7512997  0.7470274 ]]


In [ ]:
type(y)

numpy.ndarray

## 1.7 단일 텐서에서 값으로 뽑아내기

In [ ]:
loss = torch.ones(1)

In [ ]:
print(loss)
print(loss.item()) # .item()은 손실 함숫값과 같이 숫자가 하나인 텐서를 텐서가 아닌 값으로 만들어 준다.

tensor([1.])
1.0
